

main() {
  // Error is a program failure
  // Exception, can be handled

  int age;
  int dogyears = 7;

  // print(age * dogyears); <-- ERROR!
}